//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaemonMaster.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaemonMaster.Language.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string button_add_service {
            get {
                return ResourceManager.GetString("button_add_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        public static string button_credits {
            get {
                return ResourceManager.GetString("button_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string button_delete_service {
            get {
                return ResourceManager.GetString("button_delete_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string button_edit_service {
            get {
                return ResourceManager.GetString("button_edit_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export list ähnelt.
        /// </summary>
        public static string button_export {
            get {
                return ResourceManager.GetString("button_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string button_file {
            get {
                return ResourceManager.GetString("button_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import list ähnelt.
        /// </summary>
        public static string button_import {
            get {
                return ResourceManager.GetString("button_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string button_search {
            get {
                return ResourceManager.GetString("button_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Service ähnelt.
        /// </summary>
        public static string button_start_service {
            get {
                return ResourceManager.GetString("button_start_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Service ähnelt.
        /// </summary>
        public static string button_stop_service {
            get {
                return ResourceManager.GetString("button_stop_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch to Session 0 ähnelt.
        /// </summary>
        public static string button_switch_to_session_0 {
            get {
                return ResourceManager.GetString("button_switch_to_session_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot delete Daemon file!\n ähnelt.
        /// </summary>
        public static string cannot_delete_deamonfile {
            get {
                return ResourceManager.GetString("cannot_delete_deamonfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot delete registery-keys!\n ähnelt.
        /// </summary>
        public static string cannot_delete_regkeys {
            get {
                return ResourceManager.GetString("cannot_delete_regkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot load data from registry! ähnelt.
        /// </summary>
        public static string cannot_load_data_from_registry {
            get {
                return ResourceManager.GetString("cannot_load_data_from_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot load Daemon file!\n ähnelt.
        /// </summary>
        public static string cannot_load_deamonfile {
            get {
                return ResourceManager.GetString("cannot_load_deamonfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot save Daemon file!\n ähnelt.
        /// </summary>
        public static string cannot_save_deamonfile {
            get {
                return ResourceManager.GetString("cannot_save_deamonfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot start the service! ähnelt.
        /// </summary>
        public static string cannot_start_the_service {
            get {
                return ResourceManager.GetString("cannot_start_the_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service is aleady running! ähnelt.
        /// </summary>
        public static string cannot_start_the_service_already_running {
            get {
                return ResourceManager.GetString("cannot_start_the_service_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot stop the service! ähnelt.
        /// </summary>
        public static string cannot_stop_the_service {
            get {
                return ResourceManager.GetString("cannot_stop_the_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service was already stopped! ähnelt.
        /// </summary>
        public static string cannot_stop_the_service_already_stopped {
            get {
                return ResourceManager.GetString("cannot_stop_the_service_already_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently unavailable :( ähnelt.
        /// </summary>
        public static string currently_unavailable {
            get {
                return ResourceManager.GetString("currently_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data cannot be saved!\n ähnelt.
        /// </summary>
        public static string data_cannot_be_saved {
            get {
                return ResourceManager.GetString("data_cannot_be_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The UI0Detect Service cannot be started! ähnelt.
        /// </summary>
        public static string error_ui0service {
            get {
                return ResourceManager.GetString("error_ui0service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to start UI0Detect service! ähnelt.
        /// </summary>
        public static string failed_start_UI0detect_service {
            get {
                return ResourceManager.GetString("failed_start_UI0detect_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interactive processes are being blocked by a registery-key. Would you like to turn it off? (The Application cannot run without interactive processes!) ähnelt.
        /// </summary>
        public static string interactive_service_regkey_not_set {
            get {
                return ResourceManager.GetString("interactive_service_regkey_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to file is invalid or file was deleted! ähnelt.
        /// </summary>
        public static string invalid_path {
            get {
                return ResourceManager.GetString("invalid_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid values ähnelt.
        /// </summary>
        public static string invalid_values {
            get {
                return ResourceManager.GetString("invalid_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string label_filter {
            get {
                return ResourceManager.GetString("label_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max limit reached ähnelt.
        /// </summary>
        public static string max_limit_reached {
            get {
                return ResourceManager.GetString("max_limit_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem occurred ähnelt.
        /// </summary>
        public static string problem_occurred {
            get {
                return ResourceManager.GetString("problem_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service successfully started! ähnelt.
        /// </summary>
        public static string service_start_was_successful {
            get {
                return ResourceManager.GetString("service_start_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service successfully stopped! ähnelt.
        /// </summary>
        public static string service_stop_was_successful {
            get {
                return ResourceManager.GetString("service_stop_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch to Session 0 ähnelt.
        /// </summary>
        public static string switch_to_session_0 {
            get {
                return ResourceManager.GetString("switch_to_session_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TEST ENG ähnelt.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service deletion was successful! ähnelt.
        /// </summary>
        public static string the_service_deletion_was_successful {
            get {
                return ResourceManager.GetString("the_service_deletion_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service deletion was not successful! ähnelt.
        /// </summary>
        public static string the_service_deletion_was_unsuccessful {
            get {
                return ResourceManager.GetString("the_service_deletion_was_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service-installation was successful! ähnelt.
        /// </summary>
        public static string the_service_installation_was_successful {
            get {
                return ResourceManager.GetString("the_service_installation_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service-installation was not succesful! ähnelt.
        /// </summary>
        public static string the_service_installation_was_unsuccessful {
            get {
                return ResourceManager.GetString("the_service_installation_was_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DeamonMaster Version 1 ähnelt.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING ähnelt.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING: In Windows 10 you can&apos;t use your mouse or keyboard! ähnelt.
        /// </summary>
        public static string windows10_mouse_keyboard {
            get {
                return ResourceManager.GetString("windows10_mouse_keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must stop the service first ähnelt.
        /// </summary>
        public static string you_must_stop_the_service_first {
            get {
                return ResourceManager.GetString("you_must_stop_the_service_first", resourceCulture);
            }
        }
    }
}
