//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaemonMaster.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaemonMaster.Language.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All processes will be killed on shutdown (except services)! Are you sure? ähnelt.
        /// </summary>
        public static string all_processes_will_be_killed {
            get {
                return ResourceManager.GetString("all_processes_will_be_killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string button_add {
            get {
                return ResourceManager.GetString("button_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates ähnelt.
        /// </summary>
        public static string button_check_for_updates {
            get {
                return ResourceManager.GetString("button_check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        public static string button_credits {
            get {
                return ResourceManager.GetString("button_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string button_delete_service {
            get {
                return ResourceManager.GetString("button_delete_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string button_edit_service {
            get {
                return ResourceManager.GetString("button_edit_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        public static string button_export {
            get {
                return ResourceManager.GetString("button_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string button_file {
            get {
                return ResourceManager.GetString("button_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string button_help {
            get {
                return ResourceManager.GetString("button_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string button_import {
            get {
                return ResourceManager.GetString("button_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kill Service ähnelt.
        /// </summary>
        public static string button_kill_service {
            get {
                return ResourceManager.GetString("button_kill_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load data from shortcut (legacy) ähnelt.
        /// </summary>
        public static string button_load_shortcut {
            get {
                return ResourceManager.GetString("button_load_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string button_remove {
            get {
                return ResourceManager.GetString("button_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string button_search {
            get {
                return ResourceManager.GetString("button_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search file ähnelt.
        /// </summary>
        public static string button_search_file {
            get {
                return ResourceManager.GetString("button_search_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start (in session) ähnelt.
        /// </summary>
        public static string button_start {
            get {
                return ResourceManager.GetString("button_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Service ähnelt.
        /// </summary>
        public static string button_start_service {
            get {
                return ResourceManager.GetString("button_start_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Service ähnelt.
        /// </summary>
        public static string button_stop_service {
            get {
                return ResourceManager.GetString("button_stop_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch to Session 0 ähnelt.
        /// </summary>
        public static string button_switch_to_session_0 {
            get {
                return ResourceManager.GetString("button_switch_to_session_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot delete Daemon file!\n ähnelt.
        /// </summary>
        public static string cannot_delete_deamonfile {
            get {
                return ResourceManager.GetString("cannot_delete_deamonfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot delete registery-keys!\n ähnelt.
        /// </summary>
        public static string cannot_delete_regkeys {
            get {
                return ResourceManager.GetString("cannot_delete_regkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot export daemon :( ähnelt.
        /// </summary>
        public static string cannot_export_daemon {
            get {
                return ResourceManager.GetString("cannot_export_daemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot import daemon :( ähnelt.
        /// </summary>
        public static string cannot_import_daemon {
            get {
                return ResourceManager.GetString("cannot_import_daemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot load data from registry! ähnelt.
        /// </summary>
        public static string cannot_load_data_from_registry {
            get {
                return ResourceManager.GetString("cannot_load_data_from_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot load Daemon file!\n ähnelt.
        /// </summary>
        public static string cannot_load_deamonfile {
            get {
                return ResourceManager.GetString("cannot_load_deamonfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot save Daemon file!\n ähnelt.
        /// </summary>
        public static string cannot_save_deamonfile {
            get {
                return ResourceManager.GetString("cannot_save_deamonfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot start the service! ähnelt.
        /// </summary>
        public static string cannot_start_the_service {
            get {
                return ResourceManager.GetString("cannot_start_the_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service is aleady running! ähnelt.
        /// </summary>
        public static string cannot_start_the_service_already_running {
            get {
                return ResourceManager.GetString("cannot_start_the_service_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot stop the service! ähnelt.
        /// </summary>
        public static string cannot_stop_the_service {
            get {
                return ResourceManager.GetString("cannot_stop_the_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service was already stopped! ähnelt.
        /// </summary>
        public static string cannot_stop_the_service_already_stopped {
            get {
                return ResourceManager.GetString("cannot_stop_the_service_already_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is console application ähnelt.
        /// </summary>
        public static string checkbox_is_console_app {
            get {
                return ResourceManager.GetString("checkbox_is_console_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Local System account ähnelt.
        /// </summary>
        public static string checkbox_use_local_system_account {
            get {
                return ResourceManager.GetString("checkbox_use_local_system_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently unavailable :( ähnelt.
        /// </summary>
        public static string currently_unavailable {
            get {
                return ResourceManager.GetString("currently_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data cannot be saved! ähnelt.
        /// </summary>
        public static string data_cannot_be_saved {
            get {
                return ResourceManager.GetString("data_cannot_be_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Existing data will be overwritten on load!
        /// ähnelt.
        /// </summary>
        public static string data_will_be_overwritten {
            get {
                return ResourceManager.GetString("data_will_be_overwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to use the data of the shortcut? All existing data will be overwritten! ähnelt.
        /// </summary>
        public static string do_you_to_use_the_data_of_the_shortcut {
            get {
                return ResourceManager.GetString("do_you_to_use_the_data_of_the_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue pending ähnelt.
        /// </summary>
        public static string enum_continue_pending {
            get {
                return ResourceManager.GetString("enum_continue_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause pending ähnelt.
        /// </summary>
        public static string enum_pause_pending {
            get {
                return ResourceManager.GetString("enum_pause_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paused ähnelt.
        /// </summary>
        public static string enum_paused {
            get {
                return ResourceManager.GetString("enum_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Running ähnelt.
        /// </summary>
        public static string enum_running {
            get {
                return ResourceManager.GetString("enum_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start pending ähnelt.
        /// </summary>
        public static string enum_start_pending {
            get {
                return ResourceManager.GetString("enum_start_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop pending ähnelt.
        /// </summary>
        public static string enum_stop_pending {
            get {
                return ResourceManager.GetString("enum_stop_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopped ähnelt.
        /// </summary>
        public static string enum_stopped {
            get {
                return ResourceManager.GetString("enum_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The UI0Detect Service cannot be started! ähnelt.
        /// </summary>
        public static string error_ui0service {
            get {
                return ResourceManager.GetString("error_ui0service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DaemonMaster only supports local user! ähnelt.
        /// </summary>
        public static string extern_domain_user_error {
            get {
                return ResourceManager.GetString("extern_domain_user_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to start UI0Detect service! ähnelt.
        /// </summary>
        public static string failed_start_UI0detect_service {
            get {
                return ResourceManager.GetString("failed_start_UI0detect_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to create a new service! ähnelt.
        /// </summary>
        public static string failed_to_create_a_new_service {
            get {
                return ResourceManager.GetString("failed_to_create_a_new_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to enable interactive services! ähnelt.
        /// </summary>
        public static string failed_to_set_interServ {
            get {
                return ResourceManager.GetString("failed_to_set_interServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom User (experimental) ähnelt.
        /// </summary>
        public static string groupbox_custom_user {
            get {
                return ResourceManager.GetString("groupbox_custom_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services can interact with the desktop ähnelt.
        /// </summary>
        public static string interact_with_desktop {
            get {
                return ResourceManager.GetString("interact_with_desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interactive processes are being blocked by a registery-key. Would you like to turn it off? (The Application cannot run without interactive processes!) ähnelt.
        /// </summary>
        public static string interactive_service_regkey_not_set {
            get {
                return ResourceManager.GetString("interactive_service_regkey_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to file is invalid or file was deleted! ähnelt.
        /// </summary>
        public static string invalid_path {
            get {
                return ResourceManager.GetString("invalid_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The username or the password cannot be empty! ähnelt.
        /// </summary>
        public static string invalid_pw_user {
            get {
                return ResourceManager.GetString("invalid_pw_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid shortcut ähnelt.
        /// </summary>
        public static string invalid_shortcut {
            get {
                return ResourceManager.GetString("invalid_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid values ähnelt.
        /// </summary>
        public static string invalid_values {
            get {
                return ResourceManager.GetString("invalid_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. restarts reset time: ähnelt.
        /// </summary>
        public static string label_counter_reset_time {
            get {
                return ResourceManager.GetString("label_counter_reset_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depend on (Group): ähnelt.
        /// </summary>
        public static string label_depend_on_group {
            get {
                return ResourceManager.GetString("label_depend_on_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depend on (Service): ähnelt.
        /// </summary>
        public static string label_depend_on_service {
            get {
                return ResourceManager.GetString("label_depend_on_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        public static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display name: ähnelt.
        /// </summary>
        public static string label_display_name {
            get {
                return ResourceManager.GetString("label_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File path: ähnelt.
        /// </summary>
        public static string label_file_path {
            get {
                return ResourceManager.GetString("label_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string label_filter {
            get {
                return ResourceManager.GetString("label_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Restarts: ähnelt.
        /// </summary>
        public static string label_max_restarts {
            get {
                return ResourceManager.GetString("label_max_restarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter(s): ähnelt.
        /// </summary>
        public static string label_parameters {
            get {
                return ResourceManager.GetString("label_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password: ähnelt.
        /// </summary>
        public static string label_password {
            get {
                return ResourceManager.GetString("label_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kill time: ähnelt.
        /// </summary>
        public static string label_process_kill_time {
            get {
                return ResourceManager.GetString("label_process_kill_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart delay: ähnelt.
        /// </summary>
        public static string label_process_restart_delay {
            get {
                return ResourceManager.GetString("label_process_restart_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service name: ähnelt.
        /// </summary>
        public static string label_service_name {
            get {
                return ResourceManager.GetString("label_service_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use to shutdown: ähnelt.
        /// </summary>
        public static string label_shutdown_console_app {
            get {
                return ResourceManager.GetString("label_shutdown_console_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start type: ähnelt.
        /// </summary>
        public static string label_start_type {
            get {
                return ResourceManager.GetString("label_start_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username: ähnelt.
        /// </summary>
        public static string label_username {
            get {
                return ResourceManager.GetString("label_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The username or the password is incorrect! ähnelt.
        /// </summary>
        public static string login_failed {
            get {
                return ResourceManager.GetString("login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The account need the right to start as a service. Do you want to give them the right? (YOU MUST MANUALLY REMOVE THAT RIGHT!) ähnelt.
        /// </summary>
        public static string logon_as_a_service {
            get {
                return ResourceManager.GetString("logon_as_a_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max limit reached ähnelt.
        /// </summary>
        public static string max_limit_reached {
            get {
                return ResourceManager.GetString("max_limit_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want permanently delete the service? ähnelt.
        /// </summary>
        public static string msg_warning_delete {
            get {
                return ResourceManager.GetString("msg_warning_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time befor the restart counter will be reset ähnelt.
        /// </summary>
        public static string placeholder_counter_reset_time {
            get {
                return ResourceManager.GetString("placeholder_counter_reset_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Please enter a description&gt; ähnelt.
        /// </summary>
        public static string placeholder_description {
            get {
                return ResourceManager.GetString("placeholder_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Please enter a display name&gt; ähnelt.
        /// </summary>
        public static string placeholder_display_name {
            get {
                return ResourceManager.GetString("placeholder_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Click on &quot;Search file&quot; to locate the .exe, etc&gt; ähnelt.
        /// </summary>
        public static string placeholder_file_path {
            get {
                return ResourceManager.GetString("placeholder_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unlimited restarts =&gt; -1 ähnelt.
        /// </summary>
        public static string placeholder_max_restarts {
            get {
                return ResourceManager.GetString("placeholder_max_restarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 =&gt; ... ähnelt.
        /// </summary>
        public static string placeholder_process_kill_time {
            get {
                return ResourceManager.GetString("placeholder_process_kill_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time between crash and restart ähnelt.
        /// </summary>
        public static string placeholder_process_restart_delay {
            get {
                return ResourceManager.GetString("placeholder_process_restart_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Please enter a Name&gt; ähnelt.
        /// </summary>
        public static string placeholder_service_name {
            get {
                return ResourceManager.GetString("placeholder_service_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Enter Service Username&gt; ähnelt.
        /// </summary>
        public static string placeholder_username {
            get {
                return ResourceManager.GetString("placeholder_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem occurred ähnelt.
        /// </summary>
        public static string problem_occurred {
            get {
                return ResourceManager.GetString("problem_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process PID ähnelt.
        /// </summary>
        public static string process_pid {
            get {
                return ResourceManager.GetString("process_pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Ctrl+Break ähnelt.
        /// </summary>
        public static string radiobutton_use_ctrlbreak {
            get {
                return ResourceManager.GetString("radiobutton_use_ctrlbreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Ctrl+C ähnelt.
        /// </summary>
        public static string radiobutton_use_ctrlc {
            get {
                return ResourceManager.GetString("radiobutton_use_ctrlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service ähnelt.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service PID ähnelt.
        /// </summary>
        public static string service_pid {
            get {
                return ResourceManager.GetString("service_pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service successfully started! ähnelt.
        /// </summary>
        public static string service_start_was_successful {
            get {
                return ResourceManager.GetString("service_start_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service successfully stopped! ähnelt.
        /// </summary>
        public static string service_stop_was_successful {
            get {
                return ResourceManager.GetString("service_stop_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start was successful! ähnelt.
        /// </summary>
        public static string start_was_successful {
            get {
                return ResourceManager.GetString("start_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start was unsuccessful! ähnelt.
        /// </summary>
        public static string start_was_unsuccessful {
            get {
                return ResourceManager.GetString("start_was_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic ähnelt.
        /// </summary>
        public static string starttype_automatic {
            get {
                return ResourceManager.GetString("starttype_automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic with delay ähnelt.
        /// </summary>
        public static string starttype_automatic_with_delay {
            get {
                return ResourceManager.GetString("starttype_automatic_with_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        /// </summary>
        public static string starttype_disabled {
            get {
                return ResourceManager.GetString("starttype_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        public static string starttype_manual {
            get {
                return ResourceManager.GetString("starttype_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch to Session 0 ähnelt.
        /// </summary>
        public static string switch_to_session_0 {
            get {
                return ResourceManager.GetString("switch_to_session_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        public static string tabitem_advanced {
            get {
                return ResourceManager.GetString("tabitem_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dependencies ähnelt.
        /// </summary>
        public static string tabitem_dependencies {
            get {
                return ResourceManager.GetString("tabitem_dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string tabitem_general {
            get {
                return ResourceManager.GetString("tabitem_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TEST ENG ähnelt.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The process killing was successful! ähnelt.
        /// </summary>
        public static string the_process_killing_was_successful {
            get {
                return ResourceManager.GetString("the_process_killing_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service killing was unsuccessful ähnelt.
        /// </summary>
        public static string the_process_killing_was_unsuccessful {
            get {
                return ResourceManager.GetString("the_process_killing_was_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected process does not exist! ähnelt.
        /// </summary>
        public static string the_selected_process_does_not_exist {
            get {
                return ResourceManager.GetString("the_selected_process_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected process is already started! ähnelt.
        /// </summary>
        public static string the_selected_process_is_already_started {
            get {
                return ResourceManager.GetString("the_selected_process_is_already_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service deletion was successful! ähnelt.
        /// </summary>
        public static string the_service_deletion_was_successful {
            get {
                return ResourceManager.GetString("the_service_deletion_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service deletion was not successful! ähnelt.
        /// </summary>
        public static string the_service_deletion_was_unsuccessful {
            get {
                return ResourceManager.GetString("the_service_deletion_was_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service-installation was successful! ähnelt.
        /// </summary>
        public static string the_service_installation_was_successful {
            get {
                return ResourceManager.GetString("the_service_installation_was_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service-installation was not succesful! ähnelt.
        /// </summary>
        public static string the_service_installation_was_unsuccessful {
            get {
                return ResourceManager.GetString("the_service_installation_was_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DeamonMaster Version 0.2.0.0 ähnelt.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING ähnelt.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING: The user must have acces to the programm folder and the file path! ähnelt.
        /// </summary>
        public static string warning_file_access {
            get {
                return ResourceManager.GetString("warning_file_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit / Add a Process ähnelt.
        /// </summary>
        public static string window_edit_add {
            get {
                return ResourceManager.GetString("window_edit_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Windows 10 1803 or later it is no longer possible to go into the session 0 desktop!
        /// ähnelt.
        /// </summary>
        public static string windows10_1803_switch_session0 {
            get {
                return ResourceManager.GetString("windows10_1803_switch_session0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING: In Windows 10 you can&apos;t use your mouse or keyboard! ähnelt.
        /// </summary>
        public static string windows10_mouse_keyboard {
            get {
                return ResourceManager.GetString("windows10_mouse_keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must stop the service first. Do you want stop the service now ? ähnelt.
        /// </summary>
        public static string you_must_stop_the_service_first {
            get {
                return ResourceManager.GetString("you_must_stop_the_service_first", resourceCulture);
            }
        }
    }
}
